### ISSUE TITLE
find suitable bootstrap theme

### ISSUE THREAD

**Issue by paragasu** [phisoft/ticketbos-web#1]

**Comment by russel0907** [comment]
@rosclaritha 

theme 1
https://preview.uideck.com/items/softland/index.html

theme 2
https://preview.uideck.com/items/saasintro/index.html

theme 3
https://preview.uideck.com/items/gradient/index.html

theme 4
https://preview.uideck.com/items/basic/index.html

theme 5
https://preview.uideck.com/items/appland/index.html

theme 6
https://startup-tailwind.preview.uideck.com/

theme 7
https://preview.uideck.com/items/play-bootstrap/index.html

**Comment by rosclaritha** [comment]
proceed to use this template https://preview.uideck.com/items/play-bootstrap/index.html @russel0907

**Comment by russel0907** [comment]
![Screenshot 2022-08-05 at 14-57-29 Play - Free Open Source HTML Bootstrap Template by UIdeck](https://user-images.githubusercontent.com/94702093/183019956-8f58c7a8-b75c-4df8-8f2a-c09a3e376faa.png)
