### ISSUE TITLE
update main banner image

### ISSUE THREAD

**Issue by paragasu** [phisoft/ticketbos-web#12]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/27353/184285980-c8cb5178-c052-4354-80a0-6d21cc1ab4d4.png">

**Comment by rosclaritha** [comment]
@russel0907 has updated the screenshot for header.
![image](https://user-images.githubusercontent.com/30463117/184568164-b52cda8b-4106-4b93-82a4-aa6c47590a82.png)
