### ISSUE TITLE
Adjust mobile view footer

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/ticketbos-web#17]
- [x] Adjust `Features` & `Solution` to be 2 column
- [x] Adjust the social media icons to be in 1 row
<img width="448" alt="Screenshot 2022-08-15 at 10 27 18 AM" src="https://user-images.githubusercontent.com/30463117/184567364-0b59c004-9f53-47ec-918e-405b5c268e63.png">

2 column:
<img width="432" alt="Screenshot 2022-08-15 at 10 24 02 AM" src="https://user-images.githubusercontent.com/30463117/184567158-14aa60b2-372d-4034-9c48-3557ba287989.png">

1 row:
<img width="431" alt="Screenshot 2022-08-15 at 10 28 15 AM" src="https://user-images.githubusercontent.com/30463117/184567445-0e3df875-3229-418d-adc7-133a7739d623.png">

**Comment by russel0907** [comment]
![Screenshot 2022-08-15 at 14-02-57 TicketBos Ticket Booking   Management System](https://user-images.githubusercontent.com/94702093/184584450-26e85304-52f3-42f6-b1a0-80e52c14efc9.png)
