### ISSUE TITLE
Replace dashboard screenshot on advance features

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/ticketbos-web#19]
Replace the screenshot with dashboard with data. Now showing empty dashboard.

![image](https://user-images.githubusercontent.com/30463117/184784588-6657de6c-22ae-40ac-b439-f6f1c560c23a.png)

**Comment by russel0907** [comment]
![Screenshot 2022-08-16 at 12-09-22 TicketBos Ticket Booking   Management System](https://user-images.githubusercontent.com/94702093/184796078-04df82b5-9a9c-4bd1-ab92-8cf378e474db.png)
