### ISSUE TITLE
design landing page 

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/ticketbos-web#2]
- create placeholder for the website
- Weticket is a simple ticket booking management system to make ticket booking and management easier. The solution's concept is also similar to booking movie tickets (gsc).

**Comment by russel0907** [comment]
![Screenshot 2022-08-06 at 22-23-48 Weticket Ticket Booking Management System](https://user-images.githubusercontent.com/94702093/183252969-860a6bc0-9a5b-43ca-a062-2d3b5de411b1.png)
