### ISSUE TITLE
Insert web content

### ISSUE THREAD

**Issue by paragasu** [phisoft/ticketbos-web#5]
- [x] change copywriting (refer to issue https://github.com/phisoft/ticketbos-web/issues/6)
- [x] change logo
- [x] change screenshots
- [x] change colour theme to suit with logo

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/27353/183253697-09578feb-f399-478c-8a3c-d8fb86235e10.png">

**Comment by rosclaritha** [comment]
Refer to issue https://github.com/phisoft/ticketbos-web/issues/6 for the copywriting content.

**Comment by russel0907** [comment]
![Screenshot 2022-08-11 at 16-38-16 TicketBos Ticket Booking   Management System](https://user-images.githubusercontent.com/94702093/184096567-178c64a5-556f-4f1c-9595-faca7d7b8262.png)
